
test-stable:
  image: 'rust:latest'
  script:
  - rustc +stable --version && cargo +stable --version      # Print version info for debugging
  - cargo +stable test --tests --verbose --jobs 1
  - cargo +stable test --tests --verbose --jobs 1 --release
  - cargo +stable test --features doctest --doc --verbose --jobs 1
  - cargo +stable test --features doctest --doc --verbose --jobs 1 --release

  - cargo +stable test --no-default-features --tests --verbose --jobs 1
  - cargo +stable test --no-default-features --tests --verbose --jobs 1 --release
  - cargo +stable test --no-default-features --features doctest --doc --verbose --jobs 1
  - cargo +stable test --no-default-features --features doctest --doc --verbose --jobs 1 --release

  - cargo +stable test --features ascii --tests --verbose --jobs 1
  - cargo +stable test --features ascii --tests --verbose --jobs 1 --release
  - cargo +stable test --features ascii --features doctest --doc --verbose --jobs 1
  - cargo +stable test --features ascii --features doctest --doc --verbose --jobs 1 --release

test-nightly:
  image: 'rustlang/rust:nightly'
  script:
  - rustc +nightly --version && cargo +nightly --version      # Print version info for debugging
  - cargo +nighly test --tests --verbose --jobs 1
  - cargo +nighly test --tests --verbose --jobs 1 --release
  - cargo +nighly test --features doctest --doc --verbose --jobs 1
  - cargo +nighly test --features doctest --doc --verbose --jobs 1 --release

  - cargo +nighly test --no-default-features --tests --verbose --jobs 1
  - cargo +nighly test --no-default-features --tests --verbose --jobs 1 --release
  - cargo +nighly test --no-default-features --features doctest --doc --verbose --jobs 1
  - cargo +nighly test --no-default-features --features doctest --doc --verbose --jobs 1 --release

  - cargo +nighly test --features ascii --tests --verbose --jobs 1
  - cargo +nighly test --features ascii --tests --verbose --jobs 1 --release
  - cargo +nighly test --features ascii --features doctest --doc --verbose --jobs 1
  - cargo +nighly test --features ascii --features doctest --doc --verbose --jobs 1 --release
