
test-stable:
  image: 'rust:latest'
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo test --tests --verbose --jobs 1
  - cargo test --tests --verbose --jobs 1 --release
  - cargo test --features doctest --doc --verbose --jobs 1
  - cargo test --features doctest --doc --verbose --jobs 1 --release

  - cargo test --no-default-features --tests --verbose --jobs 1
  - cargo test --no-default-features --tests --verbose --jobs 1 --release
  - cargo test --no-default-features --features doctest --doc --verbose --jobs 1
  - cargo test --no-default-features --features doctest --doc --verbose --jobs 1 --release

  - cargo test --features ascii --tests --verbose --jobs 1
  - cargo test --features ascii --tests --verbose --jobs 1 --release
  - cargo test --features ascii --features doctest --doc --verbose --jobs 1
  - cargo test --features ascii --features doctest --doc --verbose --jobs 1 --release

  - cargo test --features ascii --no-default-features --tests --verbose --jobs 1
  - cargo test --features ascii --no-default-features --tests --verbose --jobs 1 --release
  - cargo test --features ascii --no-default-features --features doctest --doc --verbose --jobs 1
  - cargo test --features ascii --no-default-features --features doctest --doc --verbose --jobs 1 --release
  cache:
    - target/

test-nightly:
  image: 'rustlang/rust:nightly'
  script:
  - rustc +nightly --version && cargo +nightly --version      # Print version info for debugging
  - cargo +nightly test --tests --verbose --jobs 1
  - cargo +nightly test --tests --verbose --jobs 1 --release
  - cargo +nightly test --features doctest --doc --verbose --jobs 1
  - cargo +nightly test --features doctest --doc --verbose --jobs 1 --release

  - cargo +nightly test --no-default-features --tests --verbose --jobs 1
  - cargo +nightly test --no-default-features --tests --verbose --jobs 1 --release
  - cargo +nightly test --no-default-features --features doctest --doc --verbose --jobs 1
  - cargo +nightly test --no-default-features --features doctest --doc --verbose --jobs 1 --release

  - cargo +nightly test --features ascii --tests --verbose --jobs 1
  - cargo +nightly test --features ascii --tests --verbose --jobs 1 --release
  - cargo +nightly test --features ascii --features doctest --doc --verbose --jobs 1
  - cargo +nightly test --features ascii --features doctest --doc --verbose --jobs 1 --release

  - cargo +nightly test --features ascii --no-default-features --tests --verbose --jobs 1
  - cargo +nightly test --features ascii --no-default-features --tests --verbose --jobs 1 --release
  - cargo +nightly test --features ascii --no-default-features --features doctest --doc --verbose --jobs 1
  - cargo +nightly test --features ascii --no-default-features --features doctest --doc --verbose --jobs 1 --release
  cache:
    - target/

docs:
  image: 'rust:latest'
  script:
  - rustc --version && cargo --version
  - cargo doc --no-deps
  cache:
    - target/

clippy:
  image: 'rust:latest'
  before_script:
  - rustup component add clippy
  script:
  - cargo clippy -- -D warnings
  - cargo clippy --features ascii -- -D warnings
  - cargo clippy --no-default-features -- -D warnings
  - cargo clippy --features ascii --no-default-features -- -D warnings
  cache:
    - target/
