[package]
name = "fdt-rs"
version = "0.1.0"
authors = ["Sean Wilson <sean.wilson@ghs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.endian-type]
git = "https://github.com/spwilson2/endian-type"
branch = "dev"
default-features = false

[features]
default = ["std"]
std = []
